const mongoose = require("mongoose");

const ListingSchema = new mongoose.Schema({
  title: String,
  description: String,
  propertyPrice: String,
  afterPriceLabel: String,
  beforePriceLabel: String,
  category: String,
  type: String,
  status: String,
  address: String,
  country: String,
  state: String,
  city: String,
  neighborhood: String,
  zip: String,
  videoSource: String,
  videoId: String,
  virtualTour: String,
  images: [String], 
  pdfFile: String, 
  latitude: String,
  longitude: String,
  streetView: String,
  cameraAngle: String,
  size: String,
  lotSize: String,
  rooms: String,
  bedrooms: String,
  bathrooms: String,
  customId: String,
  garages: String,
  yearBuilt: String,
  garageSize: String,
  availableFrom: String,
  basement: String,
  extraDetails: String,
  roofing: String,
  exteriorMaterial: String,
  structureType: String,
  floors: String,
  ownerNotes: String,
  approval: String,
  interiorDetails: [String],
  outdoorDetails: [String],
  utilities: [String],
  otherFeatures: [String],
}, { timestamps: true });

module.exports = mongoose.model("Listing", ListingSchema);
